before_script:
  - hostname
  - whoami
  - sudo docker --version

stages:
  - build
  - deploy_staging
  - deploy

#
############# build ##############
#
build:
  tags: 
    - rstudio
    - labs-az-01
  stage: build
  script: 
    - echo "Building the app in staging"
    - pwd; ls -la
    - ./build-test

#
############# deploy_staging ##############
#
.deploy_staging_template: &deploy_staging_definition  # Hidden key that defines an anchor named 'deploy_staging_definition'
  stage: deploy
  script:
    - echo "Building the app in staging"
    - pwd; ls -la
    - ./build-test
    - echo "Deploy to staging server"
    - pwd; ls -la
    - cd /srv/persistent-data/docker-scripts; ./run-test-instance
  environment:
    name: staging
  only:
  - staging


deploy_staging_01:
  tags: 
    - rstudio
    - labs-az-01
  <<: *deploy_staging_definition           # Merge the contents of the 'deploy_staging_definition' alias

deploy_staging_02:
  tags: 
    - rstudio
    - labs-az-02
  <<: *deploy_staging_definition           # Merge the contents of the 'deploy_staging_definition' alias

deploy_staging_00:
  tags: 
    - rstudio
    - labs-az-00
  <<: *deploy_staging_definition           # Merge the contents of the 'deploy_staging_definition' alias

deploy_staging_15:
  tags: 
    - rstudio
    - labs-az-15
  <<: *deploy_staging_definition           # Merge the contents of the 'deploy_staging_definition' alias




#
############# deploy_production ##############
#
.deploy_production_template: &deploy_production_definition  # Hidden key that defines an anchor named 'deploy_production_definition'
  stage: deploy
  script:
    - echo "Building the production app"
    - pwd; ls -la
    - ./build-production
    - echo "Deploy to production server"
    - cd /srv/persistent-data/docker-scripts; ./run-everything
  environment:
    name: production
  when: manual
  only:
  - master

deploy_production_01:
  tags: 
    - rstudio
    - labs-az-01
  <<: *deploy_production_definition           # Merge the contents of the 'deploy_production_definition' alias

deploy_production_02:
  tags: 
    - rstudio
    - labs-az-02
  <<: *deploy_production_definition           # Merge the contents of the 'deploy_production_definition' alias

deploy_production_00:
  tags: 
    - rstudio
    - labs-az-00
  <<: *deploy_production_definition           # Merge the contents of the 'deploy_production_definition' alias

deploy_production_15:
  tags: 
    - rstudio
    - labs-az-15
  <<: *deploy_production_definition           # Merge the contents of the 'deploy_production_definition' alias



#push_to_gitlab_registry:
#  tags: 
#    - rstudio
#    - labs-az-01r
#  stage: deploy
#  script:
#    - echo "pushing image to gitlab.oit.duke.edu container registry"
#    - pwd; ls -la
#    - ./build-production
#    - echo "pushing to gitlab"
#    - sudo docker login --password $GITLAB_PW --username mccahill gitlab-registry.oit.duke.edu 
#    - sudo docker tag docker-rstudio gitlab-registry.oit.duke.edu/mccahill/docker-rstudio
#    - sudo docker push gitlab-registry.oit.duke.edu/mccahill/docker-rstudio
#    - sudo docker logout gitlab-registry.oit.duke.edu 
#  environment:
#    name: production
#  when: manual
#  only:
#  - master

