#!/bin/bash
#
# run the test/monitoring instance at port 443 
#
sudo docker kill r-studio-test-443
sudo docker rm r-studio-test-443
sudo docker run --name r-studio-test-443 \
     -d -p 127.0.0.1\:\:8787 \
     -e USERPASS=$STAGING_TEST_PASSWORD \
     -e VIRTUAL_HOST=labs-az-08.oit.duke.edu:443 \
     -e MAP_VIRTUAL_PORT=443 \
     -v /srv/persistent-data/homedirs/monitoring-user\:/home/guest \
     -i -t r-studio-test
