r <- getOption("repos")
r["CRAN"] <- "http://cran.r-project.org"
options(repos=r)

utils::install.packages("shinythemes", dependencies=TRUE )
utils::install.packages("shinydashboard", dependencies=TRUE )
utils::install.packages("miniUI", dependencies=TRUE )
utils::install.packages("shinystan", dependencies=TRUE )
utils::install.packages("rstanarm", dependencies=TRUE )
utils::install.packages("tidyposterior", dependencies=TRUE )
utils::install.packages("tidymodels", dependencies=TRUE )
utils::install.packages("forecast", dependencies=TRUE )
utils::install.packages("rstan", dependencies=TRUE )
utils::install.packages("tidybayes", dependencies=TRUE )
utils::install.packages("brms", dependencies=TRUE )
utils::install.packages("BAS", dependencies=TRUE )
